"""add full_name to users

Revision ID: 5ed837b145f0
Revises: 0001
Create Date: 2026-05-25 11:21:21.482398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ed837b145f0'
down_revision: Union[str, None] = '0001'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('audit_logs', 'ip_address',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.drop_index(op.f('idx_documents_entity'), table_name='documents')
    op.drop_index(op.f('idx_documents_purpose'), table_name='documents')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.create_unique_constraint(None, 'refresh_tokens', ['token_hash'])
    op.add_column('users', sa.Column('full_name', sa.String(), nullable=True))
    op.alter_column('users', 'password_hash',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'password_hash',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.drop_column('users', 'full_name')
    op.drop_constraint(None, 'refresh_tokens', type_='unique')
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_index(op.f('idx_documents_purpose'), 'documents', ['purpose', 'status'], unique=False)
    op.create_index(op.f('idx_documents_entity'), 'documents', ['entity_type', 'entity_id'], unique=False)
    op.alter_column('audit_logs', 'ip_address',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    # ### end Alembic commands ###
