"""add linked_accounts table (mock banking)

Revision ID: 6f3a29bbd701
Revises: 862160bce972
Create Date: 2026-07-07 19:36:53.606524

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f3a29bbd701'
down_revision: Union[str, None] = '862160bce972'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('linked_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_type', sa.Text(), nullable=False),
    sa.Column('provider', sa.Text(), server_default='MOCK', nullable=False),
    sa.Column('account_ref_masked', sa.Text(), nullable=False),
    sa.Column('display_name', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='ACTIVE', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_linked_accounts_user_id'), 'linked_accounts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_linked_accounts_user_id'), table_name='linked_accounts')
    op.drop_table('linked_accounts')
    # ### end Alembic commands ###
